acc = 0.1
decel = 0.99
asteroidSpeed = 1.5
bulletSpeed = 2.5
level = 1
health = 5
alive = true
canvas = document.getElementById("myCanvas")
canvasId = "myCanvas"
ctx = canvas.getContext("2d")
gameOver = false
gameMode = 'normal'
player = ""
asteroids = []
bullets = []
projectiles = []
newProjectiles = []
currentMousePos = {x: -1, y: -1}

firstTime = true